import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { dancingScript } from '@/utils/fonts/dancing-script';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} antialiased flex flex-col w-screen h-screen`}
            >
                <Header/>
                
                <div className="flex-grow">

                    <div className="absolute top-0 left-0 tag-font">
                        &lt;body&gt;
                    </div>

                    {children}

                    {/* <div className="absolute bottom-[2.5rem] left-0 tag-font">
                        &lt;/body&gt;
                    </div> */}

                </div>

                <Footer />
            </body>
        </html>
    );
}
