export const projectData2 = {
    myplanner: {
        title: "my planner",
        description: "React, TypeScript, Vite를 기반으로 제작한 개인 일정 관리 웹 애플리케이션입니다. 평소 종이로 작성하던 '오늘 공부 플래너'를 웹 애플리케이션으로 직접 구현하며, UI와 기능을 모두 직접 설계하고 개발하였습니다.",
        date: "2025.10 ~ 2024.11",
        function: "일간 / 주간 / 월간 단위로 할 일 등록 및 관리, 달력 안에 직접 일정 추가 및 확인, 시간별 계획을 시각적을 표현하는 UI제공, 날짜 골라서 주간 plnner UI, open api를 이용한 위치 중심 날씨 표현",
        skill: "React, TypeScript, Vite, API, Axios, Bootstrap",
        problem: "",
        solve: "",
        contribution: "100%",
        url: "https://github.com/dann0316/MyPlanner",
        sample:"/personal/myplanner.mp4",
    },
    shoeshop: {
        title: "shoe shop",
        description: "React 기반으로 제작한 신발 쇼핑몰 웹 애플리케이션입니다. 쇼핑몰에서 요구되는 기본적인 기능들을 직접 구현하며, 프론트엔드 구조 설계 및 상태 관리에 대한 이해를 높이기 위한 개인 프로젝트입니다.",
        date: "2024.09 ~ 2024.10",
        function: "상품 목록 조회, 상품 상세 페이지 확인, 장바구니 담기 및 수량 조절 및 삭제, 장바구니 내 상품 정렬 / 역정렬, 최근 본 상품 자동 저장 및 조회",
        skill: "React, Redux, Bootstrap, Fetch API, Axios",
        problem: "컴포넌트 수가 많아지면서, 특히 장바구니 기능을 만들 때 state를 효율적으로 공유하고 관리하는 데 어려움이 발생",
        solve: "React 전용 상태 관리 도구인 Redux를 도입하여 상태를 구조적으로 관리하고, 컴포넌트 간의 데이터 흐름 일관되게 유지",
        contribution: "100%",
        url: "https://github.com/dann0316/ReactShopProject",
        sample:"/personal/shoeshop.mp4",
    },
    youtubeanalyzer: {
        title: "youtube analyzer",
        description: "React 기반으로 제작한 Youtube 채널 및 영상 데이터를 분석하고, 성과도를 시각화하는 서비스 유튜버 '주언규 PD'의 Viewtrap과 유사한 기능을 구현해보는 개인 프로젝트입니다.",
        date: "2024.11 ~ 2024.12",
        function: "유튜브 영상 검색 및 조회수 / 좋아요 / 댓글 수 조회 (키워드 및 제목으로 검색), 조회수 대비 구독자 수, 업로드일 기준 조회 속도, 시청 지속율, 참여율(댓글, 좋아요) 등을 분석하여 성과도 점수화, 성과도 평가, 자동완성 기능 (검색어 추천), 검색 키워드 기반 검색 및 영상 제목 검색 지원",
        skill: "백엔드 Node.js + Express, 프론트엔드 React",
        problem: "",
        solve: "",
        contribution: "100%",
        url: "https://github.com/dann0316/YoutubeAnalyzer",
        sample:"/personal/youtubeanalyzer.png",
    },
    writeanything: {
        title: "write anything",
        description: "Next.js 기반의 커뮤니티 웹 서비스입니다. 사용자는 소셜 로그인 또는 ID/PW 방식으로 회원가입 및 로그인이 가능하며, 로그인한 유저는 본인의 게시글을 작성·수정·삭제할 수 있고, 다른 사용자의 글에는 댓글을 남길 수 있는 기본적인 커뮤니티 기능을 제공합니다.",
        date: "2024.02 ~ 2024.04",
        function: "회원가입, 소셜 로그인, ID/PW 로그인, 로그아웃, 글 발행, 글 수정, 글 목록, 댓글 발행, 댓글 수정, 댓글 삭제",
        skill: "프론트 엔드: Next.js, Tailwind / 백 엔드: Next.js / DB: MongoDB",
        problem: "",
        solve: "",
        contribution: "100%",
        url: "https://github.com/dann0316/WriteAnything",
        sample:"/personal/writeanything.mp4",
    },
    portpolio: {
        title: "portpolio",
        description: "포트폴리오 웹사이트입니다. 전체 구성은 Home, Projects, About 3개의 페이지로 이루어져 있으며, 각 페이지마다 목적에 맞는 핵심 문구와 필수 기능을 간결하게 담았습니다. 또한 페이지 전환 및 주요 요소에 Framer Motion을 활용해 간단한 (인터랙션) 애니메이션도 직접 구현하였습니다.",
        date: "2024.04 ~ 2024.05",
        function: "인삿말,text 애니메이션, 프로젝트 필터링, 상세 페이지 이동[Dynamic Route], 자기소개 및 연락처 링크",
        skill: "프론트엔드: Nextjs, Tailwind, Framer motion",
        problem: "",
        solve: "",
        contribution: "100%",
        url: "https://github.com/dann0316/PortpolioProject",
        sample:"/personal/portpolio.png",
    },
};